language: python
dist: trusty
sudo: required
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: 
  - "sudo apt-add-repository -y ppa:fish-shell/release-2"
  - "sudo apt-get update"
  - "sudo apt-get install fish"
  - "pip install -e .[dev]"
script: pytest